---

- name: Install software on DB Servers
  hosts: tag_Name_TechDay_Database
  pre_tasks:
    - name: Update repositories cache if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install the latest version of "postgresql"
      apt:
        name: postgresql
        state: present
        
  roles:
    - role: dsansible      
      action: set-policy-by-name
      policy_name: "TechDay - Database"

    #- role: deep-security.deep-security-agent
    #  action: update-configuration

    #- role: deep-security.deep-security-agent
    #  action: run-recommendation-scans     
