---
- name: Install Deep Security Agent
  hosts: tag_Name_AnsibleDemo_Database, tag_AnsibleDemo_TechDay_Reverse_Proxy, tag_AnsibleDemo_TechDay_Webserver
  roles:
    - role: deep-security.deep-security-agent
      operation: deploy
      #DSaaS
      tenant_id: ""
      tenant_password: ""
      token: ""
      force_reactivation: true
#      policy_name: "TechDay - general"
      policy_name: "[AnsibleDemo] Base policy"



       #DS on premise
      dsm_agent_download_hostname: dsm.ceur-testlab.trendmicro.de
      dsm_agent_download_port: 4119
      dsm_agent_activation_hostname: dsm.ceur-testlab.trendmicro.de
      dsm_agent_activation_port: 4120
