---
- hosts: tag_Name_TechDay_Database
  gather_facts: False
  tasks:
  - name: Update repositories cache if the last one is more than 3600 seconds ago
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install the latest version of "postgresql"
    apt:
      name: postgresql
      state: present
      
- hosts: tag_Name_TechDay_Webserver
  gather_facts: False
  tasks:
  - name: Update repositories cache if the last one is more than 3600 seconds ago
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install the latest version of "apache2"
    apt:
      name: apache2
      state: present     
      
- hosts: tag_Name_TechDay_Reverse_Proxy
  gather_facts: False
  tasks:
  - name: Update repositories cache if the last one is more than 3600 seconds ago
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install the latest version of "nginx"
    apt:
      name: nginx
      state: present      
