---

- name: Install software on DB Servers
  hosts: tag_Name_TechDay_Database
        
  roles:
    - role: deep-security.deep-security-agent      
      action: set-policy-by-name
      policy_name: "TechDay - Database"      
    
    #- role: deep-security.deep-security-agent
    #  action: update-configuration
    
    - role: deep-security.deep-security-agent
      action: run-recommendation-scans           

- name: Install software on Web Servers
  hosts: tag_Name_TechDay_Webserver
       
  roles:
    - role: deep-security.deep-security-agent
      action: set-policy-by-id
      policy_id: 663
      
    #- role: deep-security.deep-security-agent
    #  action: update-configuration      

    - role: deep-security.deep-security-agent
      action: run-recommendation-scans    

- name: Install software on reverse proxys
  hosts: tag_Name_TechDay_Reverse_Proxy    
        
  roles:
    - role: deep-security.deep-security-agent
      policy_name: TechDay - Reverse Proxy
      action: set-policy-by-name      

    #- role: deep-security.deep-security-agent
    #  action: update-configuration

    - role: deep-security.deep-security-agent
      action: run-recommendation-scans    
