---
    
- name: Terminate tagged instances
  hosts: tag_Name_TechDay_Database, tag_Name_TechDay_Reverse_Proxy, tag_Name_TechDay_Webserver
  tasks:
    - ec2_metadata_facts:
    - ec2:
        state: absent
        region: "{{ ansible_ec2_placement_region }}"
        instance_ids: "{{ ansible_ec2_instance_id }}"
      delegate_to: localhost
