---

- name: Terminate instances
  hosts: tag_Role_Database
  connection: local
  tasks:
    - name: Print all variables for each remote device
      debug: 
        var: hostvars[instance_ids]
  
    - name: Terminate instances that were previously launched
      ec2:
        state: 'absent'
        instance_ids: "{{instance_ids}}"
