---

- name: Terminate tagged instances
  hosts: tag_Name_AnsibleDemo_Database, tag_Name_AnsibleDemo_Reverse_Proxy, tag_Name_AnsibleDemo_Webserver
  tasks:
    - ec2_metadata_facts:
    - ec2:
        state: absent
        region: "{{ ansible_ec2_placement_region }}"
        instance_ids: "{{ ansible_ec2_instance_id }}"
      delegate_to: localhost
